### ISSUE TITLE
GitHub is deprecating the "setOutput" command

### ISSUE THREAD

**Issue by angusjellis** [navikt/github-app-token-generator#9]
GitHub is [deprecating the "setOutput" command](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) in favour of env files.

This means that this action will likely break on May 1st, 2023 if it isn't updated 😿

**Comment by saulotoledo** [comment]
Any plans for updating this, @christeredvartsen?

**Comment by skhalaf21** [comment]
+1

**Comment by perspilling** [comment]
@thokra-nav looks like you did some work on this issue?

**Comment by christeredvartsen** [comment]
It was fixed a while ago but I don't think we created a new release.

**Comment by christeredvartsen** [comment]
@perspilling @skhalaf21 I just released `v1.2.0` now with the fix @thokra-nav made back in January. If you use `v1` or `v1.2` you should be set. Feel free to close the issue if it seems to be working.

**Comment by skhalaf21** [comment]
thank you @christeredvartsen
